### ISSUE TITLE
Create a template for issues

### ISSUE THREAD

**Issue by jnadroj** [jnadroj/thxmx-ui#24]
Create a template for the creation of issues in order to know what the created issue is about.

Take your own considerations for a good issue template. 🚀

**Comment by Frey0-0** [comment]
assign this to me @jnadroj

**Comment by Frey0-0** [comment]
I have a raised a PR for this issue. Please review #25 @jnadroj

**Comment by jnadroj** [comment]
@Frey0-0 I have requested changes, please take a look.
