### ISSUE TITLE
Create CONTRIBUTING.md for the proyect 

### ISSUE THREAD

**Issue by jnadroj** [jnadroj/thxmx-ui#26]
# **📚 Documentation Issue Report**

## **Describe the solution you'd like**

* Currently we do not have a CONTRIBUTING.md file so it would be good to add it to the project.

---

### **Additional context**

* Take own considerations to be able to create it

**Comment by kartikjoshi267** [comment]
Please assign this to me!

**Comment by Dorcastunmise** [comment]
I'll like to work on this as well

**Comment by jnadroj** [comment]
Hello @Dorcastunmise  I have created another issue to update the readme, could you help us with this one? please! 

This is the issue #27

**Comment by Dorcastunmise** [comment]
Seen and confirmed.
