### ISSUE TITLE
Update Readme of the proyect

### ISSUE THREAD

**Issue by jnadroj** [jnadroj/thxmx-ui#27]
# **📚 Documentation Issue Report**

## **Describe the bug**

* Currently we want to update the readme so that it can redirect to the contributing file and add a little more value to this readme, 

---

## **Describe the solution you'd like**

* We can add the requirements of the project (tools we need to have installed), how to create a branch to be able to contribute and even how to push correctly to not leave the project repo to another site, this would also help people who are starting with github to contribute and feel that the project is friendly. 

---

### **Additional context**

* Take other considerations to make the readme user-friendly

**Comment by jnadroj** [comment]
@Dorcastunmise could you help us with this issue please ?

**Comment by Dorcastunmise** [comment]
Okay then. I'll start working on this. And as soon as the other guy is done, I'll link the "CONTRIBUTING.md ".

**Comment by jnadroj** [comment]
LGTM 🚀

**Comment by Dorcastunmise** [comment]
Yeah, I noticed. Worked on the assigned task already...sent a PR like an hour ago.

**Comment by jnadroj** [comment]
@Dorcastunmise I've posted some comments in this article.
